name: Build Stardew Valley Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Descargar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurar .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    # Restaurar dependencias
    - name: Restore dependencies
      run: dotnet restore

    # Compilar el proyecto sin verificar el juego
    - name: Build project
      run: |
        dotnet build --configuration Release /p:GamePath='.'
        
    # Subir el archivo DLL como artefacto
    - name: Upload mod DLL
      uses: actions/upload-artifact@v3
      with:
        name: StardewMod
        path: bin/Release/netstandard2.0/*.dll
